### ISSUE TITLE
Thanks and heads up

### ISSUE THREAD

**Issue by jassent** [Log234/azure-functions-signalr-dotnet-isolated-demo#2]
First...A thank you for organizing this. I am working my way through what you provided. Where I am stuck is invoking a "newMessage" properly from the client. This issue is that you included an appsettings.json file which has a link to your "Endpoints:SignalR". You may wish to remove that. The MultipleOutput you put together is slick - nice idea.

**Comment by Log234** [comment]
Oop, thanks for the heads up, it has been fixed.
In what way is invoking a new message giving you trouble?

**Comment by jassent** [comment]
From the javascript client this causes the signalr service in serverless mode to break the connection:
await connection.invoke("newMessage", message1, message2);

The client receives the message but immediately after then the signalr connection errors out saying the response was incomplete with a problem in the "promise."

However, this works just fine:
connection.send("newMessage", message1, message2);

The client receives the message and the connection remains intact.

I have a feeling it is the upstream hook that is causing the problem but I am not 100%. The upstream hook fires in both cases.

PS - I know but don't know why the javascript client is supposed to call the azure function directly and not use the invoke/send method. 

This [page](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0#call-hub-methods-from-the-client) has this warning:
"Calling hub methods from a client is only supported when using the Azure SignalR Service in Default mode. For more information, see Frequently Asked Questions (azure-signalr GitHub repository)."

Again, not sure why this is cause for concern.
